server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: http://order-service:8081
            predicates:
              - Path=/api/orders/**

          - id: inventory-service
            uri: http://inventory-service:8082
            predicates:
              - Path=/api/inventory/**

          - id: warehouse-service
            uri: http://warehouse-service:8083
            predicates:
              - Path=/api/warehouses/**

          - id: delivery-service
            uri: http://delivery-service:8084
            predicates:
              - Path=/api/deliveries/**

          - id: notification-service
            uri: http://notification-service:8085
            predicates:
              - Path=/api/notifications/**

          - id: recommendation-service
            uri: http://recommendation-service:8086
            predicates:
              - Path=/api/recommendations/**

management:
  endpoints:
    web:
      exposure:
        include: health,info